import Head from 'next/head'
import Image from 'next/image'

export default function Home({articles}) {
  console.log(articles);
  return (
    <div className=''>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>WELCOME HOME</p>

    </div>
  )
}
